old_sound_rabbit_mq:
    connections:
        default:
            host:     127.0.0.1
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            keepalive: true
            connection_timeout: 3
            read_write_timeout: 3
    rpc_clients:
        request:
            direct_reply_to: true
